paths:
  inbox: /srv/services/inbox
  measurements: /srv/contenedores/CONTENEDORES/CONTENEDORES/3-Medidas
  results: /srv/contenedores/CONTENEDORES/CONTENEDORES/5-Resultados
  logs: /var/log/noiseport-server

conda:
  env_name: s3_env

pipeline:
  enabled_steps:
    - queries
    - peaks
    - alarms
    - visualizations